import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { useAuth } from '../../context/AuthContext'
import { claimSession, getAllSessions, getOpenSessions, getSessionsForUser } from '../../services/firestore'
import type { Session } from '../../types/domain'
import { EmptyState } from '../../components/EmptyState'
import { SessionCard } from '../../components/SessionCard'
import { ProfileSettings } from '../profile/ProfileSettings'

export function Dashboard() {
  const { user, profile } = useAuth(); const [sessions, setSessions] = useState<Session[]>([]); const [openSessions, setOpenSessions] = useState<Session[]>([]); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => { if (!user || !profile) return; void Promise.all([profile.role === 'volunteer' ? getSessionsForUser(user.uid, 'volunteer') : profile.role === 'school' ? getSessionsForUser(user.uid, 'school') : getAllSessions(), profile.role === 'volunteer' ? getOpenSessions() : Promise.resolve([])]).then(([mine, open]) => { setSessions(mine); setOpenSessions(open); setLoading(false) }).catch(() => { setMessage('We could not load your sessions yet.'); setLoading(false) }) }, [user, profile])
  const approved = profile?.approvalStatus === 'approved'; const greeting = profile?.role === 'school' ? 'Your classroom, your invitation.' : profile?.role === 'admin' ? 'A clear view of the circle.' : 'Your next conversation starts here.'
  async function claim(id: string) { if (!user) return; try { await claimSession(id, user.uid, profile?.displayName ?? user.email ?? 'Volunteer'); setOpenSessions((current) => current.filter((session) => session.id !== id)); setMessage('Session claimed. The school will be notified.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to claim this session.') } }
  if (loading) return <div className="loading-screen">Loading your workspace...</div>
  return <><div className="workspace-heading"><div><p className="eyebrow">{profile?.role === 'school' ? 'School workspace' : profile?.role === 'admin' ? 'Admin workspace' : 'Volunteer workspace'}</p><h1>{greeting}</h1><p className="muted">{approved ? 'Thank you for making space for connection.' : 'Your application is being reviewed. We will be in touch soon.'}</p></div>{profile?.role === 'school' && approved && <Link className="button" to="/sessions/new">Create a session <span>↗</span></Link>}</div>{message && <div className="notice">{message}</div>}{profile?.role === 'volunteer' && approved && <section className="dashboard-section"><div className="section-heading"><div><p className="eyebrow">Open invitations</p><h2>Find your next classroom.</h2></div><span className="count">{openSessions.length} available</span></div>{openSessions.length ? <div className="session-grid">{openSessions.map((session) => <SessionCard key={session.id} session={session} action={<button className="button small" onClick={() => void claim(session.id)}>Claim session</button>} />)}</div> : <EmptyState title="No open sessions yet" text="New opportunities will appear here when a school creates a session that fits your availability." />}</section>}<section id="sessions" className="dashboard-section"><div className="section-heading"><div><p className="eyebrow">{profile?.role === 'admin' ? 'Operations' : 'Your calendar'}</p><h2>{profile?.role === 'school' ? 'Classroom sessions' : profile?.role === 'admin' ? 'All sessions' : 'Your sessions'}</h2></div></div>{sessions.length ? <div className="session-list">{sessions.map((session) => <SessionCard key={session.id} session={session} />)}</div> : <EmptyState title={profile?.role === 'admin' ? 'No sessions yet' : 'Your first session is waiting'} text={approved ? 'When a session is claimed or created, it will show up here.' : 'Once your application is approved, this is where your sessions will live.'} />}</section><section id="hours" className="stats-row"><div><span className="stat-value">{sessions.filter((session) => session.status === 'COMPLETED').reduce((total, session) => total + (session.durationMinutes === 60 ? 1 : 0.5), 0).toFixed(1)}</span><span className="stat-label">Volunteer hours</span></div><div><span className="stat-value">{sessions.filter((session) => session.status === 'COMPLETED').length}</span><span className="stat-label">Conversations completed</span></div><div><span className="stat-value">{sessions.filter((session) => session.status === 'CONFIRMED' || session.status === 'CLAIMED').length}</span><span className="stat-label">Coming up</span></div></section><ProfileSettings /></>
}
