import { useEffect, useState } from 'react'
import { Navigate } from 'react-router-dom'
import { useAuth } from '../../context/AuthContext'
import { getUserProfiles, updateApprovalStatus } from '../../services/firestore'
import { EmptyState } from '../../components/EmptyState'

export function AdminUsers() {
  const { profile } = useAuth(); const [users, setUsers] = useState<Awaited<ReturnType<typeof getUserProfiles>>>([]); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true); const [updating, setUpdating] = useState<string | null>(null); const [statusFilter, setStatusFilter] = useState<'pending' | 'approved' | 'rejected'>('pending')
  useEffect(() => { if (profile?.role !== 'admin') return; void getUserProfiles().then((result) => { setUsers(result.sort((left, right) => Number(right.approvalStatus === 'pending') - Number(left.approvalStatus === 'pending'))); setLoading(false) }).catch(() => { setMessage('We could not load applications right now.'); setLoading(false) }) }, [profile])
  if (profile?.role !== 'admin') return <Navigate to="/dashboard" replace />
  if (loading) return <div className="loading-screen">Loading applications...</div>
  async function setStatus(userId: string, approvalStatus: 'approved' | 'rejected') { setUpdating(userId); setMessage(''); try { await updateApprovalStatus(userId, approvalStatus); setUsers((current) => current.map((user) => user.id === userId ? { ...user, approvalStatus } : user)) } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to update this application.') } finally { setUpdating(null) } }
  const filteredUsers = users.filter((user) => user.approvalStatus === statusFilter); const schools = filteredUsers.filter((user) => user.role === 'school'); const volunteers = filteredUsers.filter((user) => user.role === 'volunteer')
  function userSection(title: string, sectionUsers: typeof users) { return <section className="approval-group"><div className="section-heading"><div><p className="eyebrow">Applications</p><h2>{title}</h2></div><span className="count">{sectionUsers.length}</span></div>{sectionUsers.length ? <div className="session-list">{sectionUsers.map((user) => <article className="session-card" key={user.id}><div className="session-info"><span className={`status status-${user.approvalStatus}`}>{user.approvalStatus}</span><h3>{user.displayName || 'Unnamed applicant'}</h3><p>{user.email}</p>{user.role === 'school' && <p>{[user.schoolName, user.schoolLocation, user.schoolSize, user.studentAgeRange].filter(Boolean).join(' · ')}</p>}</div><div className="session-action">{statusFilter === 'pending' ? <><button className="button small" disabled={updating === user.id} onClick={() => void setStatus(user.id, 'approved')}>Approve</button><button className="button small ghost" disabled={updating === user.id} onClick={() => void setStatus(user.id, 'rejected')}>Reject</button></> : <button className="button small ghost" disabled={updating === user.id} onClick={() => void setStatus(user.id, statusFilter === 'approved' ? 'rejected' : 'approved')}>{statusFilter === 'approved' ? 'Move to denied' : 'Approve again'}</button>}</div></article>)}</div> : <p className="muted">No {statusFilter} {title.toLowerCase()}.</p>}</section> }
  return <section className="form-page"><p className="eyebrow">Admin workspace</p><h1>Review applications.</h1><p className="form-intro">Pending applications are shown first. Switch views to review approved or denied applications.</p>{message && <div className="notice error">{message}</div>}<div className="approval-filters" role="group" aria-label="Application status"><button className={`filter-button ${statusFilter === 'pending' ? 'active' : ''}`} onClick={() => setStatusFilter('pending')}>Pending</button><button className={`filter-button ${statusFilter === 'approved' ? 'active' : ''}`} onClick={() => setStatusFilter('approved')}>Approved</button><button className={`filter-button ${statusFilter === 'rejected' ? 'active' : ''}`} onClick={() => setStatusFilter('rejected')}>Denied</button></div>{userSection('School coordinators', schools)}{userSection('Volunteers', volunteers)}{filteredUsers.length === 0 && <EmptyState title={`No ${statusFilter} applications`} text="Applications will appear here when they match this status." />}</section>
}
