import { useState, type FormEvent } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useAuth } from '../../context/AuthContext'
import { createSession } from '../../services/firestore'

export function SessionForm() {
  const { user } = useAuth(); const navigate = useNavigate(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('')
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!user) return; const form = new FormData(event.currentTarget); const topics = String(form.get('topics') ?? '').split(',').map((topic) => topic.trim()).filter(Boolean); const duration = Number(form.get('duration')) as 30 | 60; setBusy(true); try { await createSession({ schoolId: user.uid, classroomName: String(form.get('classroomName')), date: String(form.get('date')), startTime: String(form.get('startTime')), endTime: String(form.get('endTime')), timezone: String(form.get('timezone')), durationMinutes: duration, studentCount: Number(form.get('studentCount')), topics, teacherNotes: String(form.get('teacherNotes')), meetingUrl: String(form.get('meetingUrl') || ''), status: 'OPEN' }); navigate('/dashboard'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Unable to create session.') } finally { setBusy(false) } }
  return <section className="form-page"><Link className="back-link" to="/dashboard">← Back to overview</Link><p className="eyebrow">Create a classroom invitation</p><h1>Open a door to your classroom.</h1><p className="form-intro">Give volunteers the context they need to arrive ready and curious. You can update the session later.</p>{message && <div className="notice error">{message}</div>}<form className="long-form" onSubmit={submit}><div className="form-grid"><label>Classroom or group name<input name="classroomName" required placeholder="Grade 5 English Club" /></label><label>Student count<input name="studentCount" type="number" min="1" required placeholder="25" /></label><label>Date<input name="date" type="date" required /></label><label>Thailand start time<input name="startTime" type="time" required /></label><label>Thailand end time<input name="endTime" type="time" required /></label><label>Timezone<select name="timezone" defaultValue="Asia/Bangkok"><option>Asia/Bangkok</option><option>Asia/Manila</option><option>Asia/Singapore</option></select></label><label>Duration<select name="duration" defaultValue="30"><option value="30">30 minutes</option><option value="60">60 minutes</option></select></label><label>Grade or age <span className="optional">optional</span><input name="grade" placeholder="10-11 years old" /></label></div><label>Conversation topics <span className="optional">separate with commas</span><input name="topics" required placeholder="Family, hobbies, weekend plans" /></label><label>Teacher notes <span className="optional">optional</span><textarea name="teacherNotes" rows={4} placeholder="Anything that would help the volunteer feel prepared?" /></label><label>Meeting URL <span className="optional">Google Meet or Zoom</span><input name="meetingUrl" type="url" placeholder="https://meet.google.com/..." /></label><button className="button" disabled={busy}>{busy ? 'Creating...' : 'Publish session'} <span>↗</span></button></form></section>
}
